import { Box, type SxProps, type Theme } from "@mui/material";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconProp } from "@fortawesome/fontawesome-svg-core";
import {
  faAddressCard,
  faArrowDown,
  faArrowDownToLine,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowsRotate,
  faArrowsUpDown,
  faArrowUp,
  faArrowUpToLine,
  faBan,
  faBabyCarriage,
  faBars,
  faBell,
  faBellSlash,
  faBolt,
  faBoxArchive,
  faBoxesStacked,
  faBriefcase,
  faBriefcaseClock,
  faBuilding,
  faBuildingColumns,
  faBuildingFlag,
  faBullhorn,
  faCakeCandles,
  faCalculator,
  faCalendar,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faCalendarPen,
  faCalendarXmark,
  faCaretDown,
  faChartColumn,
  faCheck,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleCheck,
  faCircleExclamation,
  faCircleHalfStroke,
  faCircleInfo,
  faCircleMinus,
  faCircleNodes,
  faCirclePause,
  faCirclePlay,
  faCirclePlus,
  faCircleXmark,
  faClipboard,
  faClipboardCheck,
  faClock,
  faClockRotateLeft,
  faCloudArrowDown,
  faCloudArrowUp,
  faCloudCheck,
  faCloudSlash,
  faCode,
  faCoins,
  faComment,
  faCompress,
  faCopy,
  faDoorClosed,
  faDownload,
  faEllipsisVertical,
  faEnvelope,
  faEnvelopeOpen,
  faExpand,
  faEye,
  faEyeSlash,
  faFile,
  faFileArrowUp,
  faFileCirclePlus,
  faFileLines,
  faFilePdf,
  faFilter,
  faFlask,
  faFloppyDisk,
  faFolder,
  faFolderOpen,
  faFunction,
  faGauge,
  faGear,
  faGraduationCap,
  faGripVertical,
  faHand,
  faHospital,
  faHourglass,
  faHourglassEnd,
  faHourglassStart,
  faHouse,
  faIdBadge,
  faKey,
  faKitMedical,
  faLayerGroup,
  faLink,
  faThumbtack,
  faLinkSlash,
  faListCheck,
  faListUl,
  faLocationDot,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMicroscope,
  faMinus,
  faMoneyBill,
  faMoneyBills,
  faMoon,
  faNewspaper,
  faPaperPlane,
  faPause,
  faPen,
  faPenToSquare,
  faPeopleGroup,
  faPercent,
  faPersonCane,
  faPiggyBank,
  faPlay,
  faPlus,
  faPrint,
  faReceipt,
  faRectangleList,
  faRightLeft,
  faRotateLeft,
  faSitemap,
  faSliders,
  faSort,
  faSquareChevronDown,
  faSquareChevronUp,
  faStairs,
  faStamp,
  faStar,
  faSterlingSign,
  faStore,
  faSun,
  faColumns3,
  faTableCells,
  faTags,
  faTractor,
  faTrash,
  faTrashCan,
  faTriangleExclamation,
  faUmbrellaBeach,
  faUpload,
  faUpRightFromSquare,
  faUser,
  faUserCheck,
  faUserGear,
  faUserMinus,
  faUserPlus,
  faUsers,
  faUserSlash,
  faWandMagicSparkles,
  faWrench,
  faXmark,
} from "@fortawesome/pro-regular-svg-icons";

/**
 * Central icon registry — the single source of truth mapping app icon
 * names to FontAwesome glyphs (Pro, `fa-regular` style, matching JUI).
 * Keyed by the former MUI icon base-name so the migration is mechanical
 * (`<DashboardOutlinedIcon .../>` -> `<Icon name="DashboardOutlined" .../>`),
 * and any glyph choice is a one-line change here rather than a per-call-site edit.
 */
const REGISTRY = {
  AccessTime: faClock,
  AccountBalance: faBuildingColumns,
  AccountTree: faSitemap,
  Add: faPlus,
  AddCircleOutline: faCirclePlus,
  AdminPanelSettings: faUserGear,
  Agriculture: faTractor,
  AlignVerticalBottom: faArrowDownToLine,
  AlignVerticalTop: faArrowUpToLine,
  Apartment: faBuilding,
  Approval: faStamp,
  Archive: faBoxArchive,
  ArrowBack: faArrowLeft,
  ArrowDownward: faArrowDown,
  ArrowDownwardOutlined: faArrowDown,
  ArrowDropDown: faCaretDown,
  ArrowForward: faArrowRight,
  ArrowLeft: faChevronLeft,
  ArrowRight: faChevronRight,
  ArrowUpward: faArrowUp,
  ArrowUpwardOutlined: faArrowUp,
  Article: faNewspaper,
  ArticleOutlined: faNewspaper,
  Assessment: faChartColumn,
  AssessmentOutlined: faChartColumn,
  Assignment: faClipboard,
  AssignmentInd: faAddressCard,
  AssignmentOutlined: faClipboard,
  AssignmentTurnedIn: faClipboardCheck,
  AutoAwesome: faWandMagicSparkles,
  AutoFixHigh: faWandMagicSparkles,
  AutoMode: faArrowsRotate,
  Autorenew: faArrowsRotate,
  Badge: faIdBadge,
  // MUI's name for the pram. Parental leave is the only thing in
  // the product it stands for, so it earns a name of its own
  // rather than another calendar.
  ChildFriendly: faBabyCarriage,
  BeachAccess: faUmbrellaBeach,
  Biotech: faMicroscope,
  Block: faBan,
  Bolt: faBolt,
  Build: faWrench,
  Business: faBuilding,
  Cake: faCakeCandles,
  Calculate: faCalculator,
  CalendarMonth: faCalendarDays,
  Campaign: faBullhorn,
  Cancel: faCircleXmark,
  CancelOutlined: faCircleXmark,
  Category: faTags,
  ChatBubbleOutline: faComment,
  Check: faCheck,
  CheckCircle: faCircleCheck,
  CheckCircleOutline: faCircleCheck,
  Checklist: faListCheck,
  ChevronLeft: faChevronLeft,
  ChevronRight: faChevronRight,
  Clear: faXmark,
  Close: faXmark,
  CloudDone: faCloudCheck,
  CloudDownload: faCloudArrowDown,
  CloudOff: faCloudSlash,
  CloudSync: faArrowsRotate,
  CloudUpload: faCloudArrowUp,
  CloudUploadOutlined: faCloudArrowUp,
  Code: faCode,
  CompareArrows: faRightLeft,
  ContentCopy: faCopy,
  Contrast: faCircleHalfStroke,
  CurrencyPound: faSterlingSign,
  DarkMode: faMoon,
  Dashboard: faGauge,
  DashboardOutlined: faGauge,
  DateRange: faCalendarDays,
  Delete: faTrash,
  DeleteOutline: faTrashCan,
  Description: faFileLines,
  DescriptionOutlined: faFileLines,
  Diversity3: faPeopleGroup,
  DoneAll: faCheckDouble,
  DoorFront: faDoorClosed,
  Download: faDownload,
  DragIndicator: faGripVertical,
  Edit: faPen,
  EditCalendar: faCalendarPen,
  EditNote: faPenToSquare,
  EditNoteOutlined: faPenToSquare,
  EditOutlined: faPen,
  Elderly: faPersonCane,
  Error: faCircleExclamation,
  ErrorOutline: faCircleExclamation,
  Event: faCalendar,
  EventAvailable: faCalendarCheck,
  EventBusy: faCalendarXmark,
  EventRepeat: faCalendarDays,
  ExitToApp: faArrowRightFromBracket,
  ExpandLess: faChevronUp,
  ExpandMore: faChevronDown,
  FactCheck: faClipboardCheck,
  FactCheckOutlined: faClipboardCheck,
  FileOpen: faFileArrowUp,
  FileOpenRounded: faFileArrowUp,
  FileUploadOutlined: faFileArrowUp,
  FilterList: faFilter,
  Folder: faFolder,
  FolderOpen: faFolderOpen,
  FormatListBulleted: faListUl,
  Functions: faFunction,
  GroupAdd: faUserPlus,
  Groups: faPeopleGroup,
  History: faClockRotateLeft,
  HomeOutlined: faHouse,
  HourglassBottom: faHourglassEnd,
  HourglassEmpty: faHourglass,
  HourglassTop: faHourglassStart,
  HowToReg: faUserCheck,
  Hub: faCircleNodes,
  ImportExport: faArrowsUpDown,
  Info: faCircleInfo,
  InfoOutlined: faCircleInfo,
  InsertDriveFile: faFile,
  InsertDriveFileOutlined: faFile,
  Inventory: faBoxesStacked,
  Key: faKey,
  KeyboardArrowDown: faChevronDown,
  Layers: faLayerGroup,
  LightMode: faSun,
  Link: faLink,
  PushPin: faThumbtack,
  LinkOff: faLinkSlash,
  List: faListUl,
  ListAlt: faRectangleList,
  ViewList: faRectangleList,
  LocalHospital: faHospital,
  // Locations — the places an organisation administers people at. A flagged
  // building rather than `Apartment`'s plain one, which Departments already
  // has: the two sit next to each other on the Settings card, and the same
  // glyph twice reads as a mistake. `Business` is no use as an alternative —
  // it maps to faBuilding as well.
  LocationCity: faBuildingFlag,
  Lock: faLock,
  LockOpen: faLockOpen,
  LockOutlined: faLock,
  LockReset: faKey,
  Logout: faArrowRightFromBracket,
  Mail: faEnvelope,
  MailOutline: faEnvelope,
  MarkEmailRead: faEnvelopeOpen,
  MarkEmailUnread: faEnvelope,
  MedicalServices: faKitMedical,
  Menu: faBars,
  MenuOutlined: faBars,
  MonetizationOn: faMoneyBill,
  MoneyOff: faMoneyBill,
  MoreVert: faEllipsisVertical,
  NavigateBefore: faChevronLeft,
  NavigateNext: faChevronRight,
  NoteAdd: faFileCirclePlus,
  NotificationsActive: faBell,
  NotificationsNone: faBell,
  NotificationsOff: faBellSlash,
  NotificationsPaused: faBellSlash,
  OpenInNew: faUpRightFromSquare,
  Paid: faMoneyBill,
  PanToolAltOutlined: faHand,
  Pause: faPause,
  PauseCircle: faCirclePause,
  PauseCircleOutline: faCirclePause,
  Payments: faMoneyBills,
  PendingActions: faListCheck,
  People: faUsers,
  PeopleOutline: faUsers,
  Percent: faPercent,
  Person: faUser,
  PersonAdd: faUserPlus,
  PersonAddAlt1: faUserPlus,
  PersonOff: faUserSlash,
  PersonPin: faLocationDot,
  PersonRemove: faUserMinus,
  PictureAsPdf: faFilePdf,
  PlayArrow: faPlay,
  PlayCircle: faCirclePlay,
  PlayCircleOutline: faCirclePlay,
  PlaylistAddCheck: faListCheck,
  Print: faPrint,
  Publish: faUpload,
  RadioButtonUnchecked: faCircle,
  RateReview: faStar,
  Receipt: faReceipt,
  ReceiptLong: faReceipt,
  Refresh: faArrowsRotate,
  Remove: faMinus,
  RemoveCircleOutline: faCircleMinus,
  Reorder: faBars,
  Replay: faRotateLeft,
  RestartAlt: faArrowsRotate,
  Restore: faClockRotateLeft,
  Rule: faListCheck,
  Save: faFloppyDisk,
  Savings: faPiggyBank,
  Schedule: faClock,
  School: faGraduationCap,
  Science: faFlask,
  Search: faMagnifyingGlass,
  Send: faPaperPlane,
  SendOutlined: faPaperPlane,
  Settings: faGear,
  SettingsBrightness: faCircleHalfStroke,
  SettingsOutlined: faGear,
  Sort: faSort,
  SquareChevronDown: faSquareChevronDown,
  SquareChevronUp: faSquareChevronUp,
  Stairs: faStairs,
  Star: faStar,
  StarBorder: faStar,
  StarBorderOutlined: faStar,
  Storefront: faStore,
  SwapHoriz: faRightLeft,
  ViewKanban: faColumns3,
  TableView: faTableCells,
  TaskAlt: faCircleCheck,
  Today: faCalendarDay,
  Toll: faCoins,
  Tune: faSliders,
  Undo: faRotateLeft,
  Upload: faUpload,
  UploadFile: faFileArrowUp,
  Visibility: faEye,
  VisibilityOff: faEyeSlash,
  VisibilityOffOutlined: faEyeSlash,
  VisibilityOutlined: faEye,
  VpnLock: faLock,
  Warning: faTriangleExclamation,
  WarningAmber: faTriangleExclamation,
  WarningAmberOutlined: faTriangleExclamation,
  Work: faBriefcase,
  WorkHistory: faBriefcaseClock,
  WorkOutline: faBriefcase,
  ZoomOutMap: faExpand,
  ZoomInMap: faCompress,
} satisfies Record<string, IconProp>;

export type IconName = keyof typeof REGISTRY;

/** Mirror MUI icon `fontSize`; FA glyphs are 1em, so font-size drives size. */
const FONT_SIZE = {
  small: "1.25rem",
  medium: "1.5rem",
  large: "2.1875rem",
  inherit: "inherit",
} as const;

/**
 * Optical size match to MUI's `SvgIcon`. Material glyphs sit on a 24px
 * artboard with built-in padding, so their ink fills ~0.85em; FontAwesome
 * glyphs fill their box nearly edge to edge and read heavier at the same
 * nominal size. Rendering the glyph at 0.85em keeps our `fontSize` tokens
 * meaning the same as MUI's (so `small`/`medium`/`large` line up with
 * un-migrated MUI icons, e.g. the date-picker calendar) while matching
 * their visual weight. The wrapping span keeps the nominal size for layout.
 */
const GLYPH_STYLE = { fontSize: "0.85em" } as const;

/** Mirror MUI icon `color` -> theme palette. */
const COLOR = {
  inherit: "inherit",
  action: "action.active",
  disabled: "action.disabled",
  primary: "primary.main",
  secondary: "secondary.main",
  error: "error.main",
  info: "info.main",
  success: "success.main",
  warning: "warning.main",
} as const;

export type IconProps = {
  name: IconName;
  /** Mirrors MUI `fontSize`. */
  fontSize?: keyof typeof FONT_SIZE;
  /** Mirrors MUI `color` (palette key). */
  color?: keyof typeof COLOR;
  sx?: SxProps<Theme>;
  className?: string;
  /** MUI parity: accessible label — sets `aria-label` + `title`. */
  titleAccess?: string;
} & Omit<React.HTMLAttributes<HTMLSpanElement>, "color" | "className">;

/**
 * App icon. Drop-in for the former MUI icons: same `fontSize` / `color`
 * / `sx` / `className` / `titleAccess` props, plus any span HTML attrs
 * (`onClick`, `id`, `aria-*`, `role`, …) pass straight through. Renders a
 * `fa-regular` glyph that inherits `currentColor`, wrapped in a span so
 * MUI `sx` + palette `color` apply.
 */
const Icon: React.FC<IconProps> = ({
  name,
  fontSize = "medium",
  color,
  sx,
  className,
  titleAccess,
  ...rest
}) => (
  <Box
    component="span"
    className={className}
    sx={[
      {
        display: "inline-flex",
        fontSize: FONT_SIZE[fontSize],
        ...(color ? { color: COLOR[color] } : {}),
      },
      ...(Array.isArray(sx) ? sx : sx ? [sx] : []),
    ]}
    {...rest}
    {...(titleAccess ? { "aria-label": titleAccess, title: titleAccess } : {})}
  >
    <FontAwesomeIcon icon={REGISTRY[name]} fixedWidth style={GLYPH_STYLE} />
  </Box>
);

export default Icon;
